---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Some Examples from Wakefield Chapter 1

library(lasso2)
data(Prostate)
attach(Prostate)
y <- Prostate$lpsa
lcavol <- Prostate$lcavol
lweight <- Prostate$lweight
age <- Prostate$age
lbph <- Prostate$lbph
svi <- Prostate$svi
lcp <- Prostate$lcp
gleason <- Prostate$gleason
pgg45 <- Prostate$pgg45
#
#
pdf("prostfig1.pdf",height=4.5,width=7)
par(mar=c(4,4,2,1)+.1)  # bottom/left/top/right
par(mfrow=c(2,4))
plot(lcavol,lpsa,xlab="log(can vol)",ylab="log PSA")
lines(lowess(lcavol,lpsa))
plot(lweight,lpsa,xlab="log(weight)",ylab="log PSA")
lines(lowess(lweight,lpsa))
plot(age,lpsa,xlab="age",ylab="log PSA")
lines(lowess(age,lpsa))
plot(lbph,lpsa,xlab="log(BPH)",ylab="log PSA")
lines(lowess(lbph,lpsa))
boxplot(lpsa~svi,xlab="SVI",ylab="log PSA")
plot(lcp,lpsa,xlab="log(cap pen)",ylab="log PSA")
lines(lowess(lcp,lpsa))
plot(gleason,lpsa,xlab="gleason",ylab="log PSA")
lines(lowess(gleason,lpsa))
plot(pgg45,lpsa,xlab="PGS45",ylab="log PSA")
lines(lowess(pgg45,lpsa))
dev.off()
#
#
pdf("prostfig2.pdf",height=7,width=4.5)
par(mfrow=c(4,3))
par(mar=c(4,4,2,1)+.1)  # bottom/left/top/right
boxplot(lcavol~svi,ylab="log(can vol)",xlab="SVI")
plot(lcp,lcavol,ylab="log(can vol)",xlab="log(cap pen)")
lines(lowess(lcp,lcavol))
plot(gleason,lcavol,ylab="log(can vol)",xlab="gleason")
lines(lowess(gleason,lcavol))
plot(pgg45,lcavol,ylab="log(can vol)",xlab="PGS45")
lines(lowess(pgg45,lcavol))
plot(lweight,age,ylab="age",xlab="log(weight)")
lines(lowess(lweight,age))
plot(lbph,lweight,xlab="log(BPH)",ylab="log(weight)")
lines(lowess(lbph,lweight))
plot(lbph,age,ylab="age",xlab="log(BPH)")
lines(lowess(lbph,age))
boxplot(lcp~svi,ylab="lcp",ylab="log(cap pen)",
xlab="SVI")
boxplot(pgg45~svi,ylab="PGS45",xlab="SVI")
plot(gleason,lcp,ylab="log(cap pen)",xlab="gleason")
lines(lowess(gleason,lcp))
plot(lcp,pgg45,ylab="PGS45",xlab="log(cap pen)")
lines(lowess(lcp,pgg45))
plot(gleason,pgg45,ylab="PGS45",xlab="gleason")
lines(lowess(gleason,pgg45))
dev.off()


# Pharmacokinetic Theophylline example
#
library(nlme)
data(Theoph)
conc1 <- Theoph$conc[24:33]
time1 <- Theoph$Time[24:33]
#
# Fig 1.6
#
pdf("theoph-fig1.pdf",width=4.5,height=4)
plot(conc1~time1,xlab="Time (hours)",ylab="Concentration (mg/liter)",
     ylim=c(0,max(conc1)))
dev.off()
#
# Fig 1.7
#
pdf("pkcomp1.pdf",width=4.5,height=4.5)
library(diagram)
par(mar=c(.8,.8,.8,.8))
openplotmat()
elpos  <- coordinates(c(2,2))
textellipse(mid=elpos[1,],0.16,0.08,lab=c("Compartment 0"))
textempty(mid=elpos[3,],lab=c("DOSE"),box.col="white")
textellipse(mid=elpos[2,],0.16,0.08,lab=c("Compartment 1"))
# textempty(mid=elpos[4,],lab=c("CONCENTRATION"))
straightarrow(from=elpos[1,]+c(0.16,0),to=elpos[2,]+c(-0.185,0),arr.pos=1)
straightarrow(from=elpos[3,]+c(0,0.03),to=elpos[1,]+c(0,-0.11),arr.pos=1)
straightarrow(from=elpos[2,]+c(0,-0.085),to=elpos[4,]+c(0,0.055),arr.pos=1)
textplain(mid=c(0.48,.78),lab=expression(k[a]))
textplain(mid=c(0.75,.25),lab=expression(k[e]))
dev.off()
#
# Dental example
#
library(nlme)
data(Orthodont)
attach(Orthodont)
age <- Orthodont$age
distace <- Orthodont$distance
#
# Fig 1.8
#
pdf("dental.pdf",height=5,width=4.5)
plot(age,distance,type="n",xlab="Age (years)",ylab="Distance (mm)")
for (i in 1:16){
    index <- (i-1)*4+seq(1:4)
    lines(age[index],distance[index])
}
for (i in 1:11){
    index <- 64+(i-1)*4+seq(1:4)
    lines(age[index],distance[index],lty=2)
}
legend("topleft",bty="n",legend=c("Boys","Girls"),lty=c(1,2))
dev.off()
#
# Spinal bone density example
#
bone <- read.table("spinalbonedata.txt", header=T)
bone <- subset(bone, sex=="fem")
bone$ethnic <- as.factor(bone$ethnic)
bone$groupVec <- 1
bone$seqno <- 1:nrow(bone)
library(lattice)
pdf(file="spinalbone.pdf",height=5,width=4.5)
lattice.options(default.theme = "col.whitebg")
xyplot(spnbmd~age|ethnic, data = bone, groups=idnum, layout=c(2,2), aspect=1,
       xlab="Age (years)",ylab="Spinal Bone Marrow Density",
       panel=function(x,y,subscripts,groups) {
         lpoints (x,y, pch=20, col=1, cex=.3)
         ids=unique(groups[subscripts])
         for (id in ids) {
            subset=groups[subscripts]==id
            llines(x[subset], y[subset], col=1, lty=1)
         }
       }
)
dev.off()
